spring.application.name=productservice
server.port=9191

# add configuration for database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/productandcatelog
spring.datasource.username=productuser
#spring.datasource.password= here I am not using any password because giving all the access previlege to product user
spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
